package com.lovenotes.server.moment;
import com.lovenotes.server.auth.*;import com.lovenotes.server.common.*;import com.lovenotes.server.domain.*;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.time.Instant;import java.util.*;
@RestController
public class MomentController {
    private final MomentService service;public MomentController(MomentService service){this.service=service;}
    @PostMapping("/moments") ResponseEntity<ApiResponse<MomentService.MomentView>> create(@RequestAttribute(AuthFilter.ACTOR_ATTRIBUTE) Actor actor,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody CreateMomentRequest body,HttpServletRequest request){var entity=service.create(actor.userId(),key,body.command());return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.ok(service.get(actor.userId(),entity.getId()),RequestContext.requestId(request)));}
    @GetMapping("/moments/{id}") ApiResponse<MomentService.MomentView> get(@RequestAttribute(AuthFilter.ACTOR_ATTRIBUTE) Actor actor,@PathVariable UUID id,HttpServletRequest request){return ApiResponse.ok(service.get(actor.userId(),id),RequestContext.requestId(request));}
    @PatchMapping("/moments/{id}") ApiResponse<MomentService.MomentView> update(@RequestAttribute(AuthFilter.ACTOR_ATTRIBUTE) Actor actor,@PathVariable UUID id,@Valid @RequestBody UpdateMomentRequest body,HttpServletRequest request){var entity=service.update(actor.userId(),id,body.version(),body.title(),body.body(),body.occurredAt(),body.visibility());return ApiResponse.ok(service.get(actor.userId(),entity.getId()),RequestContext.requestId(request));}
    @DeleteMapping("/moments/{id}") ResponseEntity<Void> delete(@RequestAttribute(AuthFilter.ACTOR_ATTRIBUTE) Actor actor,@PathVariable UUID id,@RequestParam int version){service.trash(actor.userId(),id,version);return ResponseEntity.noContent().build();}
    @PostMapping("/moments/{id}/restore") ApiResponse<MomentService.MomentView> restore(@RequestAttribute(AuthFilter.ACTOR_ATTRIBUTE) Actor actor,@PathVariable UUID id,HttpServletRequest request){var entity=service.restore(actor.userId(),id);return ApiResponse.ok(service.get(actor.userId(),entity.getId()),RequestContext.requestId(request));}
    @GetMapping("/timeline") ApiResponse<TimelineResponse> timeline(@RequestAttribute(AuthFilter.ACTOR_ATTRIBUTE) Actor actor,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) Instant from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) Instant to,@RequestParam(defaultValue="20") int limit,HttpServletRequest request){var items=service.timeline(actor.userId(),from,to,limit);return ApiResponse.ok(new TimelineResponse(items,null,false),RequestContext.requestId(request));}
    public record CreateMomentRequest(@NotNull DomainEnums.MomentType type,@Size(max=30) String title,@NotNull @Size(max=1000) String body,@NotNull Instant occurredAt,@NotNull DomainEnums.Visibility visibility,String mood,@Size(max=3) List<String> events,List<UUID> assetIds){MomentService.CreateCommand command(){return new MomentService.CreateCommand(type,title,body,occurredAt,visibility,mood,events==null?List.of():events,assetIds==null?List.of():assetIds);}}
    public record UpdateMomentRequest(@Min(0) int version,@Size(max=30) String title,@NotNull @Size(max=1000) String body,@NotNull Instant occurredAt,@NotNull DomainEnums.Visibility visibility){}
    public record TimelineResponse(List<MomentService.MomentView> items,String nextCursor,boolean hasMore){}
}
